USE ercot_data;
LOAD DATA LOCAL INFILE '/ssd/raw_ercot_data/DAM_Hr_LMP_2011/formatted_LMPs/part-00002' INTO TABLE 2011_prices
    FIELDS TERMINATED BY ','
    LINES TERMINATED BY '\n\t\n';
LOAD DATA CONCURRENT LOCAL INFILE '/ssd/raw_ercot_data/DAM_Hr_LMP_2011/formatted_LMPs/part-00003' INTO TABLE 2011_prices
    FIELDS TERMINATED BY ','
    LINES TERMINATED BY '\n\t\n';
LOAD DATA CONCURRENT LOCAL INFILE '/ssd/raw_ercot_data/DAM_Hr_LMP_2011/formatted_LMPs/part-00004' INTO TABLE 2011_prices
    FIELDS TERMINATED BY ','
    LINES TERMINATED BY '\n\t\n';
LOAD DATA CONCURRENT LOCAL INFILE '/ssd/raw_ercot_data/DAM_Hr_LMP_2011/formatted_LMPs/part-00005' INTO TABLE 2011_prices
    FIELDS TERMINATED BY ','
    LINES TERMINATED BY '\n\t\n';
LOAD DATA CONCURRENT LOCAL INFILE '/ssd/raw_ercot_data/DAM_Hr_LMP_2011/formatted_LMPs/part-00006' INTO TABLE 2011_prices
    FIELDS TERMINATED BY ','
    LINES TERMINATED BY '\n\t\n';
LOAD DATA CONCURRENT LOCAL INFILE '/ssd/raw_ercot_data/DAM_Hr_LMP_2011/formatted_LMPs/part-00007' INTO TABLE 2011_prices
    FIELDS TERMINATED BY ','
    LINES TERMINATED BY '\n\t\n';
LOAD DATA CONCURRENT LOCAL INFILE '/ssd/raw_ercot_data/DAM_Hr_LMP_2011/formatted_LMPs/part-00008' INTO TABLE 2011_prices
    FIELDS TERMINATED BY ','
    LINES TERMINATED BY '\n\t\n';
LOAD DATA CONCURRENT LOCAL INFILE '/ssd/raw_ercot_data/DAM_Hr_LMP_2011/formatted_LMPs/part-00009' INTO TABLE 2011_prices
    FIELDS TERMINATED BY ','
    LINES TERMINATED BY '\n\t\n';
LOAD DATA CONCURRENT LOCAL INFILE '/ssd/raw_ercot_data/DAM_Hr_LMP_2011/formatted_LMPs/part-00010' INTO TABLE 2011_prices
    FIELDS TERMINATED BY ','
    LINES TERMINATED BY '\n\t\n';
LOAD DATA CONCURRENT LOCAL INFILE '/ssd/raw_ercot_data/DAM_Hr_LMP_2011/formatted_LMPs/part-00011' INTO TABLE 2011_prices
    FIELDS TERMINATED BY ','
    LINES TERMINATED BY '\n\t\n';
LOAD DATA CONCURRENT LOCAL INFILE '/ssd/raw_ercot_data/DAM_Hr_LMP_2011/formatted_LMPs/part-00012' INTO TABLE 2011_prices
    FIELDS TERMINATED BY ','
    LINES TERMINATED BY '\n\t\n';
LOAD DATA CONCURRENT LOCAL INFILE '/ssd/raw_ercot_data/DAM_Hr_LMP_2011/formatted_LMPs/part-00013' INTO TABLE 2011_prices
    FIELDS TERMINATED BY ','
    LINES TERMINATED BY '\n\t\n';
LOAD DATA CONCURRENT LOCAL INFILE '/ssd/raw_ercot_data/DAM_Hr_LMP_2011/formatted_LMPs/part-00014' INTO TABLE 2011_prices
    FIELDS TERMINATED BY ','
    LINES TERMINATED BY '\n\t\n';
LOAD DATA CONCURRENT LOCAL INFILE '/ssd/raw_ercot_data/DAM_Hr_LMP_2011/formatted_LMPs/part-00015' INTO TABLE 2011_prices
    FIELDS TERMINATED BY ','
    LINES TERMINATED BY '\n\t\n';
LOAD DATA CONCURRENT LOCAL INFILE '/ssd/raw_ercot_data/DAM_Hr_LMP_2011/formatted_LMPs/part-00016' INTO TABLE 2011_prices
    FIELDS TERMINATED BY ','
    LINES TERMINATED BY '\n\t\n';

